### ISSUE TITLE
关于论文中的数据集的实用性

### ISSUE THREAD

**Issue by guoxixi1982** [chuanting/STDenseNet#1]
您好，拜读了您关于流量预测的论文，很受启发。但是论文中用到的那个意大利米兰的数据集，是把城市划分为规整的网格状进行数据收集的，这种划分方法看起来确实很规整，但是这种划分方法是不是会存在以下问题啊？

1. 实际中基站的覆盖范围都是很不规则的，流量预测的目的应该是预测每个基站覆盖范围下的实时流量需求情况，以便基站端实时按需调整其资源分配，避免资源浪费，如何解决您这论文中正方形网格流量预测和实际基站覆盖范围不规则的矛盾啊？您考虑过这点没。

2. 米兰那个数据集是把城市划分为网格统计的，因为基站端并不能精确知道终端的位置信息，那这个数据集在收集的时候，是不是强制每个终端都打开GPS定位后收集的数据啊，如果是这样的话，实际网络中基站端是不知道终端精确位置信息的啊（并非每个终端始终都打开GPS定位），这又是一个论文中的假设和实际网络运行是不一致的一个矛盾点吧。

3. 感觉如果考虑实际基站覆盖不规则的情况，那流量预测就不能使用您论文中提到的CNN方法了，即把每一个时刻的城市流量看做一张图像，而把一段时间内整个城市的流量看做一段视频。

感觉您这篇论文的假设和实际网络的情况存在很大的不一致，不知道您怎么看待这个问题，期盼您的回复和指点。

**Comment by chuanting** [comment]
不好意思，最近更新code才看到你的问题。关于你的疑问：

1. 方法是根据数据来的，数据是grid-based，那么方法就可以是grid-based。你当然可以采用非grid-based方法，也就是说，不采用卷积的形式，这个是完全可以的。比如：用传统的LSTM也可以解决流量预测问题。如果电信公司按照就是按照时空范围对城市进行划分，然后他们想知道未来每个区域的流量信息，那么就可以采用grid-based方法，这个不存在问题。所以，要看具体的数据以及解决的问题。
2.如何收集数据并不是我们关心的，这个问题，如果能咨询电信相关公司的人员，可能会有满意的答案。关于这一点，非常抱歉。
3.是否采用CNN，要看数据。如果你的数据只是几个基站的流量信息，那么我建议采用非CNN的方法；如果你的数据是网格的，那么，采用CNN的方法会有非常好的结果。不管是无线流量预测，还是交通流量预测，采用CNN的方法，都能取得比较好的结果。具体可以看一下AAAI 18, AAAI 19上关于流量预测相关的文章。

论文中只有一个假设：那就是假设每个cell的流量看成了基站的流量，因为它覆盖的面积是235米×235米。实际应用我们的算法时候，这个粒度（区域面积）是可以自由控制的。
